server:
  port: 8090

spring:
  config:
    name: atsuc-dubbo

dubbo:
  application:
    name: atsuc-dubbo
    version: 1.0.0
  registry:
#    address: N/A # - 无zookeeper可配置 N/A 走直连模式测试
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: cn.atsuc.dubbo.api
