server:
  port: 80

spring:
  application:
    name: cloud-consumer-openFeign-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true # 优先使用ip进行注册
        service-name: ${spring.application.name}
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000
#          cloud-payment-service:
#            connect-timeout: 2000
#            read-timeout: 2000
            # 同事有多个服务名称，寻找粒度最细的
            #开启httpclient5
      httpclient:
        hc5:
          enabled: true
          #开启压缩特性
      compression:
        request:
          enabled: true
          min-request-size: 2048
          mime-types: text/html,application/xml,application/json # 触发加载类型
        response:
          enabled: true
          # 开启circuitbreaker和分组激活
      circuitbreaker:
        enabled: true
#        group:
#          enabled: true # 使用线程池时：设为false新启线程和原来主线程脱离了。
          # 没开分组永远不用分组的配置。精确优先、分组次之(开了分组)、默认最后
# 日志输出
logging:
  level:
    cn:
      atsuc:
        cloud:
          apis:
            PayFeignApi:
              debug
#  Resilience4j CircuitBreaker 按照次数：COUNT_BASED 的例子
#  6次访问中当执行方法的失败率达到50%时CircuitBreaker将进入开启OPEN状态(保险丝跳闸断电)拒绝所有请求。
#  等待5秒后，CircuitBreaker 将自动从开启OPEN状态过渡到半开HALF_OPEN状态，允许一些请求通过以测试服务是否恢复正常。
#  如还是异常CircuitBreaker 将重新进入开启OPEN状态；如正常将进入关闭CLOSE闭合状态恢复正常处理请求。
#    1. 基于计数滑动窗口
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        failure-rate-threshold: 50 # 设置50%的调用失败时打开断路器，超过失败请求百分⽐CircuitBreaker变为OPEN状态。
#        sliding-window-size: 6 # 滑动窗⼝的⼤⼩配置COUNT_BASED表示6个请求，配置TIME_BASED表示6秒
#        minimum-number-of-calls: 6  #断路器计算失败率或慢调用率之前所需的最小样本(每个滑动窗口周期)。如果minimumNumberOfCalls为10，则必须最少记录10个样本，然后才能计算失败率。如果只记录了9次调用，即使所有9次调用都失败，断路器也不会开启。
#        automatic-transition-from-open-to-half-open-enabled: true  # 并允许一些请求通过以测试服务是否恢复正常
#        wait-duration-in-open-state: 5s # 从OPEN到HALF_OPEN状态需要等待的时间是否启用自动从开启状态过渡到半开状态，默认值为true。如果启用，CircuitBreaker将自动从开启状态过渡到半开状态
#        permitted-number-of-calls-in-half-open-state: 2 # 半开状态允许的最大请求数，默认值为10。在半开状态下，CircuitBreaker将允许最多permittedNumberOfCallsInHalfOpenState个请求通过，如果其中有任何一个请求失败，CircuitBreaker将重新进入开启状态。
#        record-exceptions:
#          - java.lang.Exception


#    2. 基于时间滑动窗口
#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s  # 神坑的位置，timelimiter 默认限制远程1s，超于1s就超时异常，配置了降级，就走降级逻辑
#  circuitbreaker:
#    configs:
#      default:
#        failure-rate-threshold: 50
#        slow-call-duration-threshold: 2s
#        slow-call-rate-threshold: 30
#        sliding-window-type: TIME_BASED
#        sliding-window-size: 2
#        minimum-number-of-calls: 2 # 断路器计算失败或调用之前所需要的最小洋文（滑动周期）
#        permitted-number-of-calls-in-half-open-state: 2 # 半开状态允许的最大请求书
#        wait-duration-in-open-state: 5s
#        record-exceptions:
#          - java.lang.Throwable

# 3. Bulkhead
#resilience4j:
#  bulkhead:
#    instances:
#      cloud-payment-service:
#        base-config: default
#    configs:
#      default:
#        max-concurrent-calls: 2 # 允许间隔并发线程执行的最大数量
#        max-wait-duration: 1s # 当达到并发调用数量时，新的线程的阻塞时间，我只愿意等待1秒，过时不候进舱壁兜底fallback
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 20s

# 4. 线程池
#resilience4j:
#  thread-pool-bulkhead:
#    configs:
#      default:
#        core-thread-pool-size: 1
#        max-thread-pool-size: 1
#        queue-capacity: 1
##        max-thread-pool-size : 1 + queue-capacity: 1 = 2     1个在max+1个在队列，第3个来报错
#    instances:
#        cloud-payment-service:
#          base-config: default
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s # timelimiter默认限制远程1s，超过报错不好演示效果所以加上10秒


#5. 限流
resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 2 # 在一次刷新周期内，允许执行的最大请求数
        limit-refresh-period: 1s # 限流器每隔limitRefreshPeriod刷新一次，将允许处理的最大请求数量重置为limitForPeriod
        timeout-duration: 1s # 线程等待权限的默认等待时间
    instances:
      cloud-payment-service:
        base-config: default


# zipkin图形展现地址和采样率设置
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。