server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri:
            lb://cloud-payment-service              # 动态注册
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
#            - After=2024-07-14T16:53:41.281448+08:00[Asia/Shanghai]
#            - Before=2024-07-14T16:53:41.281448+08:00[Asia/Shanghai]
#            - Between=2024-07-14T16:53:41.281448+08:00[Asia/Shanghai], 2024-07-14T17:53:41.281448+08:00[Asia/Shanghai]
#            - Cookie=username,atsuc
#            - Header=X-Request-Id, \d+
#            - Host=**.atsuc.cn
#            - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
#            - RemoteAddr= 169.254.213.1/24 # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
#            - My=diamond

        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri:
            lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
#            - After=2024-07-14T16:53:41.281448+08:00[Asia/Shanghai]
#            - Before=2024-07-14T17:53:41.281448+08:00[Asia/Shanghai]

        - id: pay_routh3
          uri:
            lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/filter/** #  1-1 断言，路径相匹配的进行路由
#            - Path=/gateway/filter/** # 1-2
#             - Path=/temp/next/{segment}  # 断言，为配合SetPath测试，{segment}的内容最后被SetPath取代
          filters:
            - My=atsuc
#            - SetPath=/pay/gateway/{segment}  # {segment}表示占位符，你写abc也行但要上下一致
#            - RedirectTo=302, https://blog.atsuc.cn/en # 访问http://localhost:9527/pay/gateway/filter跳转到https://blog.atsuc.cn/en
#            - PrefixPath=/pay # 1-2 http://localhost:9527/pay/gateway/filter
#            - AddRequestHeader=X-Request-atsuc1, atsucValue1  # 请求头kv，若一头含有多参则重写一行设置
#            - AddRequestHeader=X-Request-atsuc2, atsucValue2
#            - RemoveRequestHeader=sec-fetch-site  # 删除请求头sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode, Blue-updatebyatsuc # 将请求头sec-fetch-mode对应的值修改为Blue-updatebyatsuc
#            - AddRequestParameter=customerId,9527001 # 新增请求参数Parameter：k ，v
#            - RemoveRequestParameter=customerName   # 删除url请求参数customerName，你传递过来也是null
#            - AddResponseHeader=X-Response-atsuc, BlueResponse # 新增请求参数X-Response-atsuc并设值为BlueResponse
#            - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
#            - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除