server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        import-check:
          enabled: false
#消费者将要去访问的微服务名称(nacos微服务提供者叫什么你写什么)
service-url:
  nacos-user-service: http://nacos-payment-provider

  # SpringCloud 2021版本之后，需要用以下方式导入nacos的配置文件

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true